// SARD PDF DIAGNOSTIC — a stage ledger for the PDF opening pipeline. OBSERVATION ONLY.
//
// The previous report proved the book file is reachable (42 MB fetched, 200 OK, three times) and
// that pdf.js never instantiated — its two top-level `await fetch(...)` CSS loads never appeared in
// 255 recorded fetches. It could not say WHY, because ES module loading does not go through
// `window.fetch`, so the exact failing step was invisible.
//
// This module closes that hole two ways:
//
//   1. A STAGE LEDGER. Every step from the click to the first rendered page is declared UP FRONT, so
//      a step that never runs is reported as NOT ENTERED rather than simply being absent. Absence of
//      evidence and evidence of absence are different things, and last time we only had the first.
//
//   2. A CHAIN PROBE that re-walks the pdf.js dependency chain one link at a time — fetch the module
//      bytes, import the module, fetch each CSS file, construct the worker — capturing the real
//      exception at whichever link breaks.
//
// TIMING OF THE PROBE MATTERS. It runs only AFTER the application's own attempt has finished, never
// before. Importing a module populates the module cache, so probing first could make the real
// attempt succeed and hide the very defect we are hunting.
//
// The ledger machinery itself lives in ./stageLedger — it is shared with the EPUB rendering
// pipeline so both ledgers print identically and neither can drift from the other.
import { diagNote } from "./diag";
import { errShape, makeLedger, renderStageList, type Stage } from "./stageLedger";

export type { Stage, StageState } from "./stageLedger";

/** Declared up front: a stage that never runs must still appear, marked NOT ENTERED. */
const STAGE_DEFS: [string, string][] = [
  ["open.requested", "User opened a book (reader asked to open a target)"],
  ["library.row", "Library row loaded from the database (book_get)"],
  ["path.resolved", "File path resolved from the row"],
  ["asset.url", "Asset URL generated by convertFileSrc()"],
  ["controller.open", "FoliateController.open() called"],
  ["book.fetch", "Book bytes fetched over the asset protocol"],
  ["book.make", "makeBook(): File constructed and format detected"],
  ["pdfjs.import", "Dynamic import of foliate-js/pdf.js"],
  ["pdfjs.core", "Static import of vendor/pdfjs/pdf.mjs (the engine)"],
  ["pdfjs.css", "pdf.js top-level CSS loads (text_layer / annotation_layer)"],
  ["pdfjs.worker", "pdf.worker.mjs loaded / Worker constructed"],
  ["pdfjs.document", "PDFDocumentProxy created (getDocument resolved)"],
  ["pdfjs.page1", "First page obtained and rendered"],
];

let attemptActive = false;
let probeRan = false;

const ledger = makeLedger(STAGE_DEFS, (tier, msg, data) => diagNote("pdf.stage", tier, msg, data));

export function pdfDiagReset(): void {
  probeRan = false;
  ledger.reset();
}

export const stageEnter = (key: string, meta: Record<string, unknown> = {}): void => ledger.enter(key, meta);
export const stageOk = (key: string, meta: Record<string, unknown> = {}): void => ledger.ok(key, meta);
export const stageFail = (key: string, e: unknown, meta: Record<string, unknown> = {}): void => ledger.fail(key, e, meta);

/**
 * Some stages cannot be observed from outside the engine. Saying so is not the same as saying they
 * failed, and conflating the two would make the report cry wolf on a perfectly healthy machine —
 * measured: the first version reported stage 13 FAILED while the PDF was visibly on screen.
 */
export const stageUnobservable = (key: string, reason: string, meta: Record<string, unknown> = {}): void =>
  ledger.unobservable(key, reason, meta);

/**
 * Every PDF attempt made in this session, oldest first. The ledger is reset per attempt, so without
 * this a PDF attempt was DESTROYED by the next book the tester opened — and the instructions ask them
 * to try the PDF twice and then start read-aloud on another book, which is exactly the sequence that
 * would have thrown the evidence away. Measured: after opening a PDF and then an EPUB, the PDF ledger
 * showed the EPUB's attempt and every pdf.js stage read NOT ENTERED.
 */
const archived: { at: string; label: string; stages: Stage[] }[] = [];

/** Mark that a PDF open is in flight, so the chain probe knows to run afterwards. */
export function pdfAttemptStarted(meta: Record<string, unknown>): void {
  const cur = ledger.stages();
  const prev = cur.find((s) => s.key === "open.requested");
  if (String(prev?.meta?.format ?? "") === "pdf" && prev?.state !== "NOT ENTERED" && archived.length < 12) {
    archived.push({
      at: new Date().toISOString(),
      label: String(prev?.meta?.title ?? prev?.meta?.filePath ?? "(unnamed PDF)").slice(0, 80),
      stages: cur.map((s) => ({ ...s, meta: { ...s.meta } })),
    });
  }
  pdfDiagReset();
  attemptActive = true;
  stageEnter("open.requested", meta);
  // For a PDF, run the chain probe once the real attempt has had time to finish — whether it threw,
  // hung, or "succeeded" without rendering. Deliberately AFTER, never before: importing a module
  // populates the cache, and probing first could make the real attempt succeed and hide the defect.
  if (meta.format === "pdf") {
    setTimeout(() => { void probePdfChain("scheduled after the PDF open attempt"); }, 15_000);
  }
}

export const pdfAttemptActive = (): boolean => attemptActive;

/**
 * Watch for the first rendered page.
 *
 * A PDF paints to a canvas, so its appearance is the only honest evidence that the pipeline reached
 * the end. Without this, stages 12-13 would read NOT ENTERED even on a machine where PDFs work
 * perfectly, and the report could not tell a healthy pipeline from a broken one — a diagnostic that
 * looks alarming everywhere is no diagnostic at all.
 */
export async function watchFirstPage(container: HTMLElement): Promise<void> {
  const started = Date.now();
  // The page canvas is NOT a child of the container: the fixed-layout renderer paints each page
  // inside its own iframe, so a container-only search finds nothing even when the PDF is rendering
  // perfectly. Measured — the first version of this check reported a false FAILURE on a machine
  // where the PDF was on screen. Search the container AND every same-origin iframe document.
  const findCanvas = (): HTMLCanvasElement | null => {
    const direct = container.querySelector("canvas") as HTMLCanvasElement | null;
    if (direct && direct.width > 0) return direct;
    for (const f of Array.from(document.querySelectorAll("iframe"))) {
      let doc: Document | null = null;
      try { doc = (f as HTMLIFrameElement).contentDocument; } catch { continue; } // cross-origin
      const c = doc?.querySelector("canvas") as HTMLCanvasElement | null;
      if (c && c.width > 0) return c;
    }
    return null;
  };
  for (let i = 0; i < 60; i++) {
    const c = findCanvas();
    if (c && c.height > 0) {
      stageOk("pdfjs.document", { evidence: "a rendered canvas implies getDocument resolved" });
      stageOk("pdfjs.page1", { width: c.width, height: c.height, msAfterOpen: Date.now() - started });
      return;
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  // Only now is a failure claim honest: 15 s with no painted canvas anywhere in the document tree.
  stageUnobservable("pdfjs.document", "no direct hook into getDocument from outside the engine");
  stageUnobservable("pdfjs.page1", "no painted canvas found within 15s, but this renderer does not always expose one — treat as UNKNOWN, not failure", { iframes: document.querySelectorAll("iframe").length });
}

// ---------------------------------------------------------------------------------------------
// THE CHAIN PROBE
//
// Walks the same dependency chain pdf.js walks, one link at a time, so the break is named rather
// than inferred. Each link is attempted independently and its real exception recorded.
// ---------------------------------------------------------------------------------------------
const base = () => new URL("/foliate-js/vendor/pdfjs/", location.href).toString();

async function probeFetch(label: string, url: string): Promise<Record<string, unknown>> {
  const t = performance.now();
  try {
    const r = await fetch(url);
    const buf = await r.arrayBuffer();
    // First bytes tell us whether the server returned the MODULE or an HTML error page — a 200 that
    // is secretly index.html is a failure mode that a status check alone would call success.
    const head = new TextDecoder().decode(new Uint8Array(buf.slice(0, 48))).replace(/\s+/g, " ");
    return {
      label, url, ok: r.ok, status: r.status, bytes: buf.byteLength,
      contentType: r.headers.get("content-type"),
      firstBytes: head,
      looksLikeHtml: /^\s*<(!doctype|html)/i.test(head),
      ms: Math.round(performance.now() - t),
      outcome: "COMPLETED",
    };
  } catch (e) {
    return { label, url, outcome: "REJECTED", ms: Math.round(performance.now() - t), ...errShape(e) };
  }
}

export async function probePdfChain(reason: string): Promise<void> {
  if (probeRan) return;
  probeRan = true;
  diagNote("pdf.probe", "MEASURED", `chain probe starting (${reason})`);

  // LINK 1 — are the engine's bytes actually retrievable over the app protocol?
  const core = await probeFetch("pdf.mjs (engine)", base() + "pdf.mjs");
  diagNote("pdf.probe", "MEASURED", "LINK 1 — fetch pdf.mjs", core);
  const worker = await probeFetch("pdf.worker.mjs", base() + "pdf.worker.mjs");
  diagNote("pdf.probe", "MEASURED", "LINK 2 — fetch pdf.worker.mjs", worker);
  const css1 = await probeFetch("text_layer_builder.css", base() + "text_layer_builder.css");
  diagNote("pdf.probe", "MEASURED", "LINK 3 — fetch text_layer_builder.css", css1);
  const css2 = await probeFetch("annotation_layer_builder.css", base() + "annotation_layer_builder.css");
  diagNote("pdf.probe", "MEASURED", "LINK 4 — fetch annotation_layer_builder.css", css2);

  // LINK 5 — MODULE INSTANTIATION. This is the step `window.fetch` cannot see and the previous
  // report was therefore blind to. A dynamic import failure here is the prime suspect.
  const tImp = performance.now();
  try {
    const mod = await import(/* @vite-ignore */ base() + "pdf.mjs");
    const lib = (globalThis as unknown as { pdfjsLib?: Record<string, unknown> }).pdfjsLib;
    diagNote("pdf.probe", "MEASURED", "LINK 5 — import pdf.mjs SUCCEEDED", {
      ms: Math.round(performance.now() - tImp),
      moduleKeys: Object.keys(mod ?? {}).slice(0, 12),
      globalPdfjsLib: !!lib,
      version: (lib?.version as string) ?? "unknown",
    });
    stageOk("pdfjs.core", { via: "chain probe" });

    // LINK 6 — the Worker itself. pdf.js constructs one from workerSrc; if the module loads but the
    // Worker cannot start, getDocument hangs or throws with a very different signature.
    try {
      const w = new Worker(base() + "pdf.worker.mjs", { type: "module" });
      await new Promise((res) => setTimeout(res, 400));
      w.terminate();
      diagNote("pdf.probe", "MEASURED", "LINK 6 — Worker constructed and terminated cleanly");
      stageOk("pdfjs.worker", { via: "chain probe" });
    } catch (e) {
      diagNote("pdf.probe", "MEASURED", "LINK 6 — Worker construction FAILED", errShape(e));
      stageFail("pdfjs.worker", e, { via: "chain probe" });
    }
  } catch (e) {
    diagNote("pdf.probe", "MEASURED", "LINK 5 — import pdf.mjs FAILED", {
      ms: Math.round(performance.now() - tImp),
      ...errShape(e),
      note: "This is the step that window.fetch cannot observe. If the fetch of pdf.mjs above SUCCEEDED but this failed, the bytes are reachable and the failure is in parsing/instantiating the module.",
    });
    stageFail("pdfjs.core", e, { via: "chain probe" });
  }

  // LINK 7 — Rust-side file facts, straight from disk, bypassing the web layer entirely.
  try {
    const { invoke } = await import("@tauri-apps/api/core");
    const files = await invoke("diag_probe_assets");
    diagNote("pdf.probe", "MEASURED", "LINK 7 — on-disk vendored files (from Rust)", { files });
  } catch (e) {
    diagNote("pdf.probe", "UNKNOWN", "LINK 7 — could not read on-disk file facts", errShape(e));
  }
  attemptActive = false;
}

// ---------------------------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------------------------
/**
 * ATTEMPT COMPARISON — for the reported "first open fails, second open of the same file succeeds".
 *
 * A ledger per attempt is not enough to answer that: the question is what was DIFFERENT. This puts
 * the attempts side by side — how far each got, where each stopped, and how long each stage took —
 * so the difference is read off the report rather than reasoned about. It states differences only;
 * it does not explain them, because the explanation is what the evidence is for.
 */
function renderAttemptComparison(): string {
  const all = [...archived.map((a) => ({ label: a.at, stages: a.stages })), { label: "most recent", stages: ledger.stages() }];
  const pdfOnly = all.filter((a) => String(a.stages.find((s) => s.key === "open.requested")?.meta?.format ?? "") === "pdf");
  const L: string[] = [];
  L.push("=".repeat(78));
  L.push("PDF ATTEMPT COMPARISON");
  L.push("=".repeat(78));
  L.push("");
  if (pdfOnly.length < 2) {
    L.push(`Only ${pdfOnly.length} PDF attempt was recorded in this session — there is nothing to compare.`);
    L.push("A second attempt on the SAME file is what makes the 'first fails, second works' report");
    L.push("answerable, so please open the failing PDF twice before saving the report.");
    L.push("");
    return L.join("\r\n");
  }
  const furthest = (st: Stage[]) => [...st].reverse().find((s) => s.state === "COMPLETED");
  const stopped = (st: Stage[]) => st.find((s) => s.state === "FAILED") ?? st.find((s) => s.state === "ENTERED");
  L.push("  #   furthest completed                     stopped at");
  pdfOnly.forEach((a, i) => {
    const f = furthest(a.stages), s = stopped(a.stages);
    L.push(
      `  ${String(i + 1).padEnd(3)} ${(f ? `${f.id} — ${f.title}` : "NONE").slice(0, 38).padEnd(38)} ` +
        `${s ? `${s.id} — ${s.title} (${s.state === "FAILED" ? "FAILED" : "never completed"})` : "nothing left unfinished"}`,
    );
  });
  L.push("");
  // Per-stage differences: the same stage, attempt by attempt. Only stages that DIFFER are printed —
  // a table of identical rows hides the one row that matters.
  L.push("  Stages whose outcome or duration DIFFERED between attempts:");
  let printed = 0;
  for (let i = 0; i < pdfOnly[0].stages.length; i++) {
    const cells = pdfOnly.map((a) => a.stages[i]);
    const states = cells.map((c) => c?.state ?? "NOT ENTERED");
    const times = cells.map((c) => (c?.enteredAt != null && c?.endedAt != null ? c.endedAt - c.enteredAt : null));
    const stateDiffers = new Set(states).size > 1;
    const timeDiffers = times.some((t, k) => k > 0 && t != null && times[0] != null && Math.abs(t - (times[0] ?? 0)) > 250);
    if (!stateDiffers && !timeDiffers) continue;
    printed++;
    L.push(`    Stage ${cells[0]?.id ?? i + 1} — ${cells[0]?.title ?? "?"}`);
    cells.forEach((c, k) => {
      L.push(`      attempt ${k + 1}: ${states[k]}${times[k] != null ? `  (${times[k]} ms)` : ""}` +
        (c?.error ? `  REASON: ${c.error.name}: ${c.error.message}` : ""));
    });
  }
  if (!printed) {
    L.push("    NONE — every stage reached the same outcome in the same time on every attempt.");
    L.push("    If one attempt failed and another succeeded, the difference is NOT in these stages.");
  }
  L.push("");
  return L.join("\r\n");
}

export function renderStages(): string {
  const parts: string[] = [];
  // Earlier attempts first, so the report reads in the order the tester lived it.
  archived.forEach((a, i) =>
    parts.push(renderStageList(`PDF PIPELINE — STAGE LEDGER — EARLIER ATTEMPT #${i + 1} (${a.label}, ${a.at})`, a.stages)),
  );
  // Name the most recent ledger by WHAT IT ACTUALLY IS. Every book open resets this ledger, so the
  // last one is often an EPUB — and an EPUB open shown under a "PDF PIPELINE" heading with stages
  // 8-13 reading NOT ENTERED reads exactly like a PDF that died at stage 8. Measured on a healthy
  // machine: opening a PDF twice and then an EPUB produced precisely that misleading page.
  const liveFormat = String(ledger.stages().find((s) => s.key === "open.requested")?.meta?.format ?? "");
  const liveTitle =
    liveFormat === "pdf"
      ? `PDF PIPELINE — STAGE LEDGER — MOST RECENT PDF ATTEMPT (attempt #${archived.length + 1})`
      : archived.length
        ? "MOST RECENT BOOK OPENED — NOT A PDF (stages 8-13 do not apply to it; the PDF attempts are above)"
        : "PDF PIPELINE — STAGE LEDGER";
  parts.push(ledger.render(liveTitle));
  parts.push(renderAttemptComparison());
  return parts.join("\r\n");
}

export const pdfStages = (): Stage[] => ledger.stages();
export const pdfAttempts = (): { at: string; label: string; stages: Stage[] }[] => archived;
