#!/usr/bin/env node
// PROBE-ONLY — build the book the runtime gate reads. Throwaway branch.
//
// The committed fixtures are deliberately tiny: they exist to test import and parsing, and the
// largest is 25 KB spread over 80 near-empty sections. A gate that delivers a real click at a real
// coordinate needs the opposite — a section with enough prose to FILL the viewport, so that a click
// in the middle of the window lands on rendered text rather than on margin. An earlier probe drew
// its conclusions from 321-character sections and measured nothing but blank space.
//
// It is generated by the project's own `buildEpub`, not hand-rolled, so the subject is a book Sard's
// own fixture pipeline considers well-formed.
import { writeFileSync } from "node:fs";
import { buildEpub } from "../tests/fixtures/generate.mjs";

const OUT = new URL("../public/__probe/book.epub", import.meta.url);

// Arabic, because Sard is an Arabic-first reader and RTL pagination is the case worth measuring.
const PARA =
  "في قديم الزمان كان هناك كاتب يجلس كل مساء إلى مكتبه الصغير يكتب ما رآه في النهار، " +
  "وكان يؤمن أن الكلمات إذا صدقت بقيت، وأن القارئ يعرف الصدق حين يقرؤه ولو بعد حين. ";

const chapters = Array.from({ length: 8 }, (_, i) => ({
  id: `c${i}`,
  href: `c${i}.xhtml`,
  title: `الفصل ${i + 1}`,
  // ~40 paragraphs a section: several screens of text at any reasonable font size, so pagination
  // has something to paginate and a mid-window click has something to hit.
  body: Array.from({ length: 40 }, () => `<p>${PARA.repeat(3)}</p>`).join("\n"),
}));

const bytes = buildEpub({
  title: "كتاب الاختبار",
  creator: "سرد",
  language: "ar",
  dir: "rtl",
  chapters,
  ncx: chapters.map((c) => ({ label: c.title, href: c.href })),
  nav: chapters.map((c) => ({ label: c.title, href: c.href })),
});

writeFileSync(OUT, bytes);
console.log(`[probe] subject: ${bytes.length} bytes, ${chapters.length} sections -> ${OUT.pathname}`);
